# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Azure Pipelines Maven Build
trigger:
- main

pool:
  name: 'Dev'

steps:
# First install Maven
- powershell: |
    steps:
- powershell: |
    $mavenVersion = "3.8.6"
    $mavenZip = "apache-maven-$mavenVersion-bin.zip"
    $installDir = "$env:USERPROFILE\maven"
    
    # Download and install Maven
    Invoke-WebRequest -Uri "https://archive.apache.org/dist/maven/maven-3/$mavenVersion/binaries/$mavenZip" -OutFile "$env:TEMP\$mavenZip"
    Expand-Archive -Path "$env:TEMP\$mavenZip" -DestinationPath "$installDir"
    
    # Add to PATH for current job
    $mavenPath = "$installDir\apache-maven-$mavenVersion\bin"
    Write-Host "##vso[task.prependpath]$mavenPath"
  displayName: 'Install Maven'

# Then run build
- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    