# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Azure Pipelines Maven Build
trigger:
- main

pool:
  name: 'Dev'  # Your self-hosted agent pool name

variables:
  MAVEN_VERSION: '3.8.6'
  MAVEN_HOME: '$(Agent.ToolsDirectory)/maven'

steps:
- task: PowerShell@2
  displayName: 'Install Maven'
  inputs:
    targetType: 'inline'
    script: |
      # Create tools directory if it doesn't exist
      New-Item -ItemType Directory -Force -Path "$(Agent.ToolsDirectory)" | Out-Null
      
      # Download Maven
      $mavenZip = "apache-maven-$(MAVEN_VERSION)-bin.zip"
      Write-Host "Downloading Maven $(MAVEN_VERSION)..."
      Invoke-WebRequest -Uri "https://archive.apache.org/dist/maven/maven-3/$(MAVEN_VERSION)/binaries/$mavenZip" -OutFile "$env:TEMP\$mavenZip"
      
      # Extract Maven
      Write-Host "Installing Maven to $(MAVEN_HOME)..."
      Expand-Archive -Path "$env:TEMP\$mavenZip" -DestinationPath "$(MAVEN_HOME)"
      
      # Add Maven to PATH
      $mavenPath = "$(MAVEN_HOME)\apache-maven-$(MAVEN_VERSION)\bin"
      Write-Host "##vso[task.prependpath]$mavenPath"
      
      # Verify installation
      Write-Host "Maven version:"
      & "$mavenPath\mvn.cmd" --version

- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'